#@follow_tag(registry-proxy.engineering.redhat.com/rh-osbs/openshift-golang-builder:rhel_8_golang_1.23)
FROM brew.registry.redhat.io/rh-osbs/openshift-golang-builder:rhel_8_golang_1.23 AS builder
COPY . /workspace/
WORKDIR /workspace/
ENV GOEXPERIMENT strictfipsruntime
ENV BUILDTAGS containers_image_ostree_stub exclude_graphdriver_devicemapper exclude_graphdriver_btrfs containers_image_openpgp exclude_graphdriver_overlay include_gcs include_oss strictfipsruntime
ENV BIN velero-plugin-for-mtc
RUN GO111MODULE=auto CGO_ENABLED=1 GOOS=linux go build -mod=readonly -v -installsuffix "static" -tags "$BUILDTAGS" -o _output/$BIN ./velero-plugins

FROM registry.redhat.io/ubi8/ubi-minimal:latest
RUN mkdir /plugins
COPY --from=builder /workspace/_output/$BIN /plugins/
USER 65534:65534
ENTRYPOINT ["/bin/bash", "-c", "cp /plugins/* /target/."]

LABEL \
        com.redhat.component="openshift-migration-velero-plugin-for-mtc-container" \
        version="v1.8.7" \
        name="rhmtc/openshift-migration-velero-plugin-for-mtc-rhel8" \
        summary="Migration Toolkit for Containers Velero Plugin For MTC" \
        maintainer="Migration Team <ocp-migrate-team@redhat.com>" \
        License="ASL 2.0" \
        io.k8s.display-name="Migration Toolkit for Containers" \
        io.openshift.tags="migration" \
        io.k8s.description="Migration Toolkit for Containers Velero Plugin For MTC" \
        io.openshift.build.commit.id="e9aae8203280635ffadd7d60a2f02dff310f8e40" \
        io.openshift.build.source-location="https://github.com/migtools/velero-plugin-for-mtc" \
        io.openshift.build.commit.url="https://github.com/migtools/velero-plugin-for-mtc/commit/e9aae8203280635ffadd7d60a2f02dff310f8e40"
